#!/usr/bin/env python3
"""G-A057 보상 단일변수 일괄 탐색 패키지 빌더 (2026-09-29, Codex 작업 지시).

실행 목록은 tools/go2_g_a057_sweep_plan.py 가 정한다(NEW_TRAIN 행만 여기서 돈다).  각 실행은 발행된
G-A055 v2 패키지의 러너·배포 코드·평가기·registry·G-A033 sentinel 을 **바이트 그대로** 쓰고, 다음만 바꾼다.

  candidate/quadruped_rewards.py          A048 보상에서 한 항만 바꾼 값 (배포 템플릿에 값만 렌더)
  reference/*_quadruped_rewards.py        A048 보상 (reward_only.diff 가 한 줄 변경을 보이게)
  expected_rewards.json                   candidate = 그 실행의 보상, baseline = sentinel 정책(G-A033)의 보상
  run_config.env                          WORK_ID·KEEP·결과 ZIP 이름·SINGLE_CHANGE_* 만 교체
  experiment.json, README.txt             짧은 실행 설명 (채택·승급 대상 아님)
  PACKAGE_SHA256SUMS.txt                  shared + 위 파일을 펼친 트리 전체의 해시 (러너가 시작할 때 검증)

ZIP 구조: go2_g_a057/{run_sweep.sh, sweep_order.txt, SWEEP_PLAN.{json,md}, SWEEP_README.txt, SWEEP_SHA256SUMS.txt,
                     shared/…, runs/<key>/…}
    python -B tools/build_go2_g_a057_sweep_package.py          # 빌드 + 발행(upload/G-A057/current)
    python -B tools/build_go2_g_a057_sweep_package.py --check  # 빌드만, 파일 쓰지 않음
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GO2 = ROOT / "workspace/training/quadruped"
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(GO2))
import go2_g_a057_sweep_plan as planmod  # noqa: E402
from go2_tuning_config import REWARD_NAMES, reward_dict, render_reward_source  # noqa: E402

PREFIX = "go2_g_a057/"
RELEASE = "GO2_G_A057_a048_single_var_sweep_v1"
UPLOAD = GO2 / "upload/G-A057/current"
LAUNCHER = ROOT / "tools/go2_g_a057_run_sweep.sh"
PREREG_JSON = GO2 / "reports/evidence/go2_g_a057_sweep_plan/PREREGISTRATION.json"
PREREG_MD = GO2 / "reports/evidence/go2_g_a057_sweep_plan/PREREGISTRATION.md"
RUNNER = "server_run_go2_candidate_iter_pinned.sh"
OVERLAY = ("candidate/quadruped_rewards.py", "reference/baseline_quadruped_rewards.py",
           "reference/reward_base_quadruped_rewards.py", "expected_rewards.json", "run_config.env",
           "experiment.json", "README.txt", "PACKAGE_SHA256SUMS.txt")
FIXED_TIME = (2026, 9, 29, 0, 0, 0)


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def source_payload() -> dict[str, bytes]:
    z = zipfile.ZipFile(planmod.SOURCE_PACKAGE)
    out = {}
    for info in z.infolist():
        if info.is_dir():
            continue
        name = info.filename[len(planmod.SOURCE_PREFIX):]
        out[name] = z.read(info)
    return out


def six(weights: dict) -> dict[str, float]:
    return {k: float(weights[k]) for k in REWARD_NAMES}


def run_config(template: str, key: str, row: dict, base6: dict) -> str:
    name, value = row["variable"], float(row["value"])
    repl = {
        "WORK_ID": "G-A057",
        "RUN_ID": f"train_G-A057-Go2_a048_{key}_1000",
        "EXPERIMENT_SLUG": f"go2_g_a057_{key}",
        "KEEP_DIR_NAME": f"go2_g_a057_{key}",
        "RESULT_ZIP_NAME": f"GO2_G_A057_{key.upper()}_RESULT.zip",
        "DONE_MARKER": f"'[DONE] GO2_G_A057_{key.upper()}_RESULT_READY'",
        "TMUX_NAME": f"go2_g_a057_{key}",
        "SINGLE_CHANGE_NAME": name,
        "SINGLE_CHANGE_FROM": f"{base6[name]:g}",
        "SINGLE_CHANGE_TO": f"{value:g}",
    }
    lines = []
    for line in template.splitlines():
        if line.startswith("# generated by"):
            lines.append("# generated by tools/build_go2_g_a057_sweep_package.py (G-A057 sweep arm); do not edit")
            continue
        m = re.match(r"^([A-Z_]+)=", line)
        if m and m.group(1) in repl:
            lines.append(f"{m.group(1)}={repl.pop(m.group(1))}")
        else:
            lines.append(line)
    if repl:
        raise ValueError(f"run_config template lacks {sorted(repl)}")
    return "\n".join(lines) + "\n"


def arm_files(src: dict[str, bytes], row: dict, base6: dict, sentinel6: dict, prereg_sha: str) -> dict[str, bytes]:
    key, name, value = row["key"], row["variable"], float(row["value"])
    cand6 = dict(base6)
    cand6[name] = value
    changed = [k for k in REWARD_NAMES if cand6[k] != base6[k]]
    if changed != [name]:
        raise ValueError(f"{key}: must change exactly {name}, changed {changed}")
    if cand6 != six(row["rewards"]):
        raise ValueError(f"{key}: plan rewards {row['rewards']} differ from rendered {cand6}")
    template = src["candidate/quadruped_rewards.py"].decode("utf-8")
    cand_src = render_reward_source(template, cand6)
    base_src = render_reward_source(template, base6)
    if reward_dict(cand_src) != cand6 or reward_dict(base_src) != base6:
        raise ValueError(f"{key}: rendered reward file does not parse back")
    expected = {"baseline": sentinel6, "candidate": cand6}
    experiment = {
        "schema": "go2_sweep_arm_v1", "work_id": "G-A057", "run_key": key,
        "purpose": "보상 변수별 값 변화에 따른 행동·성능 반응 데이터 수집. 개선을 전제하지 않는다. 채택·승급·공식 제출 판정 대상 아님.",
        "promotion": "forbidden_sweep_data_only",
        "reward_base": {"label": planmod.BASE_LABEL, "arm": planmod.BASE_ARM, "rewards": base6},
        "single_change": {"name": name, "from": base6[name], "to": value},
        "rewards": cand6,
        "training": {"seed": 42, "num_envs": 4096, "max_iterations": 1000, "from_scratch": True},
        "evaluation": {"checkpoint_iter": 900, "seeds": [101, 202, 303], "case_count": 69,
                       "sentinel": "G-A033 stored arm, 5 cases (runner default)"},
        "runner": f"{RUNNER} from upload/G-A055/current (v2) bytes unchanged, --inner, GO2_STAGE=full",
        "plan_row": row,
        "preregistration": {"path": "go2_g_a057/PREREGISTRATION.json", "sha256": prereg_sha, "row": key,
                            "reader": "tools/go2_g_a057_prereg_readout.py"},
    }
    readme = (f"G-A057 sweep arm {key}\n"
              f"A048 보상에서 {name} 한 항만 {base6[name]:g} -> {value:g}. 학습 seed 42, 4096 env, 1000 iter, 평가 iter 900, 69 case.\n"
              "이 폴더는 run_sweep.sh 가 펼쳐서 쓴다. 혼자 실행하지 않는다. 결과는 반응 데이터이며 채택·승급 대상이 아니다.\n")
    files = {
        "candidate/quadruped_rewards.py": cand_src.encode("utf-8"),
        "reference/baseline_quadruped_rewards.py": base_src.encode("utf-8"),
        "reference/reward_base_quadruped_rewards.py": base_src.encode("utf-8"),
        "expected_rewards.json": (json.dumps(expected, indent=2) + "\n").encode("utf-8"),
        "run_config.env": run_config(src["run_config.env"].decode("utf-8"), key, row, base6).encode("utf-8"),
        "experiment.json": (json.dumps(experiment, ensure_ascii=False, indent=1) + "\n").encode("utf-8"),
        "README.txt": readme.encode("utf-8"),
    }
    return files


def shared_files(src: dict[str, bytes]) -> dict[str, bytes]:
    return {k: v for k, v in src.items() if k not in OVERLAY}


def sums(files: dict[str, bytes]) -> bytes:
    return "".join(f"{sha(files[k])}  {k}\n" for k in sorted(files)).encode("utf-8")


def guide(new_rows: list[dict], zip_sha: str | None) -> str:
    n = len(new_rows)
    arms = "\n".join(f"  {r['key']:34s} {r['variable']} {r['value']:g}" for r in new_rows)
    return f"""GO2 G-A057 보상 단일변수 일괄 탐색 — 다른 PC 실행·재개 안내
================================================================

목적: A048 보상에서 한 항씩 바꾼 학습 {n}개를 순서대로 돌려 변수별 반응 데이터를 모은다.
      개선을 전제하지 않는다. 승자 값을 합치거나 다음 값을 추가하지 않는다. 채택·공식 제출 판정 대상이 아니다.
      재사용·기준 공유 행은 돌지 않는다(근거: go2_g_a057/SWEEP_PLAN.md).

0. 필요한 환경 (공식 서버와 같게 — 다르면 결과 차이를 보상 효과로만 읽지 않는다)
   - Linux(Ubuntu), bash·tmux·sha256sum·unzip, NVIDIA GPU + nvidia-smi.
   - Isaac Lab v2.3.x(Isaac Sim 5.1)이 /workspace/IsaacLab 에 있거나, 다른 위치면 ISAACLAB_SH=<경로>/isaaclab.sh 로 알려 준다.
   - /workspace 가 쓰기 가능해야 한다(러너가 /workspace/_keep 에 결과를 쓴다).
   - 서버 기준 GPU는 RTX 5080 16 GB, 4096 env 다. VRAM 이 작으면 학습이 메모리 부족으로 실패할 수 있고,
     로봇 수를 줄이면 서버 결과와 비교할 수 없으므로 이 패키지는 4096 env 고정이다.
   - 디스크: 실행 하나당 수 GB. 남은 공간이 20 GB 미만이면 멈춘다(GO2_SWEEP_MIN_FREE_GB 로 조정).

1. 올리기
   {RELEASE}.zip  SHA256 {zip_sha or '(발행 시 기록)'}
   /workspace/{RELEASE}.zip 에 둔다.

2. 실행 — 한 줄
   unzip -oq /workspace/{RELEASE}.zip -d /workspace && bash /workspace/go2_g_a057/run_sweep.sh

   목록만 보기:   bash /workspace/go2_g_a057/run_sweep.sh --list
   진행 보기:     tmux attach -t go2_g_a057
   상태 표:       /workspace/_keep/go2_g_a057_sweep/SWEEP_STATUS.tsv
   재개:          같은 명령을 다시 친다. 검증된 완료 실행은 건너뛰고, 부분 결과는 GO2_RESUME=1 로 이어 간다.

3. 무엇이 도는가 (실행 {n}개, 순서대로)
{arms}
   실행마다: 학습 1000 iter -> iter 900 고정 -> 69 case(평가 seed 101/202/303 x 32 env) -> G-A033 sentinel 5 case
   -> 영상 10편 -> 결과 ZIP. 러너는 G-A055 v2 의 것을 바이트 그대로 쓴다.
   예상: 서버 GPU 기준 한 실행 약 95분 -> 약 {n * 95 // 60}시간 {n * 95 % 60}분. 다른 GPU에서는 달라진다(보장 아님).

4. 실패와 중단 — 실행 상태와 평가 판정은 다르다
   - 이 러너는 평가 결과가 나쁘다는 이유로 멈추거나 건너뛰지 않는다. 걷지 않는 정책도 69 case 를 끝까지 잰다.
     평가 후 후보 제외는 판독 단계(tools/go2_g_a057_prereg_readout.py, go2_g_a057/PREREGISTRATION.json)에서만 한다.
   - 상태 표의 단어:
       완료           DONE / SKIP_DONE (FULL_69_COMPLETE)
       실행 안전 중단 SAFETY_STOP_NONFINITE(학습 loss 비유한 — 평가하지 않음) / SKIP_SAFETY_STOPPED, 그리고 아래 ABORT_*
       실행 실패      RUN_ERROR(러너 오류) / COLLECTION_FAILED(수집 미완 — 다시 치면 이어 간다) / RUN_ERROR_MATERIALIZE / BLOCKED_EXISTING_RESULT
   - 한 실행이 실패하면 로그와 종료코드를 상태 표에 남기고 다음 실행으로 간다.
   - 전체를 멈추는 경우: 디스크 부족(20), 다른 학습/재생 프로세스(21), Isaac Lab·GPU 없음(22),
     학습 시작 전 실패(23, 공통 환경 문제), 두 실행 연속 학습 실패(24), 패키지 체크섬 불일치(25).
   - 학습 도중 끊긴 실행은 러너가 보존하고 멈춘다(INTERRUPTED_TRAINING_PRESERVED, 종료코드 9). 그 실행을 처음부터
     다시 하려면 보존본을 내려받은 뒤 해당 폴더를 옮기고 다시 실행한다. 이 러너는 기존 결과를 지우지 않는다.
   - 결과 ZIP 만 있고 폴더가 없으면 덮어쓰지 않고 BLOCKED 로 적는다.

5. 가져올 것 (각 실행)
   /workspace/_keep/go2_g_a057_<key>/            (폴더 전체: 학습 로그·report.html·env.yaml·checkpoint·평가 CSV·영상)
   /workspace/_keep/GO2_G_A057_<KEY>_RESULT.zip + .sha256
   /workspace/_keep/go2_g_a057_sweep/            (상태 표·환경 기록·실행 로그)
   로컬 C:\\dev\\Nconnect\\workspace\\_keep\\ 에 같은 이름으로 둔 뒤
   python -B tools/go2_g_a057_sweep_compare.py 로 비교표·그래프를 만든다
   (출력 workspace/training/quadruped/reports/evidence/go2_g_a057_sweep_compare/).

6. 규정
   공식 서버가 아닌 PC의 학습은 탐색용이다. 제출 정책은 서버 학습 이력과 대조되므로 서버에서 다시 학습한다.
   배포 학습 코드는 수정하지 않았다(보상 가중치만 다르다).
"""


def build() -> tuple[bytes, dict]:
    plan = planmod.plan()
    src = source_payload()
    base6 = six(plan["base_env_rewards"])
    sentinel6 = six(json.loads(src["expected_rewards.json"])["baseline"])
    new_rows = [r for r in plan["runs"] if r["status"] == "NEW_TRAIN"]
    if any(r["status"] == "EVAL_ONLY" for r in plan["runs"]):
        raise ValueError("EVAL_ONLY rows need a manual evaluation path; not packaged automatically")
    shared = shared_files(src)
    files: dict[str, bytes] = {}
    for k, v in shared.items():
        files["shared/" + k] = v
    order = []
    prereg = PREREG_JSON.read_bytes().replace(b"\r\n", b"\n")
    pre = json.loads(prereg)
    if sorted(pre["rows"]) != sorted(r["key"] for r in new_rows):
        raise ValueError("PREREGISTRATION rows differ from the NEW_TRAIN rows")
    files["PREREGISTRATION.json"] = prereg
    files["PREREGISTRATION.md"] = PREREG_MD.read_bytes().replace(b"\r\n", b"\n")
    for row in new_rows:
        arm = arm_files(src, row, base6, sentinel6, sha(prereg))
        tree = {**shared, **arm}
        arm["PACKAGE_SHA256SUMS.txt"] = sums(tree)
        for k, v in arm.items():
            files[f"runs/{row['key']}/{k}"] = v
        cfg = arm["run_config.env"].decode("utf-8")
        keep = re.search(r"^KEEP_DIR_NAME=(.*)$", cfg, re.M).group(1)
        zipn = re.search(r"^RESULT_ZIP_NAME=(.*)$", cfg, re.M).group(1)
        order.append(f"{row['key']} {keep} {zipn}")
    files["sweep_order.txt"] = ("\n".join(order) + "\n").encode("utf-8")
    files["run_sweep.sh"] = LAUNCHER.read_bytes().replace(b"\r\n", b"\n")
    files["SWEEP_PLAN.json"] = (json.dumps(plan, ensure_ascii=False, indent=1) + "\n").encode("utf-8")
    files["SWEEP_PLAN.md"] = planmod.markdown(plan).encode("utf-8")
    files["SWEEP_README.txt"] = guide(new_rows, None).encode("utf-8")
    files["SWEEP_SHA256SUMS.txt"] = sums({k: v for k, v in files.items()})
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name in sorted(files):
            info = zipfile.ZipInfo(PREFIX + name, FIXED_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (0o755 if name.endswith(".sh") else 0o644) << 16
            z.writestr(info, files[name])
    return buf.getvalue(), {"plan": plan, "new_rows": new_rows, "files": files}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    data, info = build()
    zsha = sha(data)
    print(f"arms {len(info['new_rows'])}, files {len(info['files'])}, zip {len(data)} bytes, sha256 {zsha}")
    if args.check:
        return 0
    UPLOAD.mkdir(parents=True, exist_ok=True)
    (UPLOAD / f"{RELEASE}.zip").write_bytes(data)
    (UPLOAD / f"{RELEASE}.zip.sha256").write_text(f"{zsha}  {RELEASE}.zip\n", encoding="utf-8", newline="\n")
    (UPLOAD / "GO2_G_A057_RUN_GUIDE.txt").write_text(guide(info["new_rows"], zsha), encoding="utf-8", newline="\n")
    print(f"published {UPLOAD / (RELEASE + '.zip')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
