#!/usr/bin/env python3
"""G-A058 보상 무변경 재학습 패키지 빌더 (2026-09-30, Claude 제안 + Codex 합의).

근거·순서·판독: workspace/training/quadruped/upload/plan/GO2_OTHER_PC_SEQUENCE_PROPOSAL_20260930.md
다른 PC에서 G-A057 나머지 11행보다 먼저 돈다.  보상은 바꾸지 않는다.

  a048_seed42   A048 학습 env.yaml 보상, 학습 seed 42   (다른 PC의 동일 보상 비교 기준)
  a043_seed43   A043 학습 env.yaml 보상, 학습 seed 43   (A043 계단 이득·우회전 결함 재현)
  a043_seed44   A043 학습 env.yaml 보상, 학습 seed 44

G-A057 빌더와 같은 방식으로 G-A055 v2 패키지의 러너·배포 코드·평가기·registry·G-A033 sentinel 을
바이트 그대로 쓰고, 행마다 보상 파일·run_config.env(TRAIN_SEED 포함)·설명 파일만 바꾼다.
러너 표기용 SINGLE_CHANGE_* 는 v10(G-A045/A046)처럼 train_seed 를 쓴다(러너는 표기만 하고 검사하지 않는다).
    python -B tools/build_go2_g_a058_replicate_package.py          # 빌드 + 발행(upload/G-A058/current)
    python -B tools/build_go2_g_a058_replicate_package.py --check  # 빌드만
"""
from __future__ import annotations

import argparse
import io
import json
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GO2 = ROOT / "workspace/training/quadruped"
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(GO2))
import build_go2_g_a057_sweep_package as a057  # noqa: E402
import go2_g_a057_sweep_plan as planmod  # noqa: E402
from go2_tuning_config import REWARD_NAMES, reward_dict, render_reward_source  # noqa: E402

WORK_ID = "G-A058"
PREFIX = "go2_g_a058/"
RELEASE = "GO2_G_A058_replicate_a048s42_a043s43s44_v1"
UPLOAD = GO2 / "upload/G-A058/current"
LAUNCHER = ROOT / "tools/go2_g_a058_run_sweep.sh"
PROPOSAL = "workspace/training/quadruped/upload/plan/GO2_OTHER_PC_SEQUENCE_PROPOSAL_20260930.md"
FIXED_TIME = (2026, 9, 30, 0, 0, 0)

# key, 기준 라벨, 기준 회차 폴더, 학습 seed — 실행 순서 그대로
ROWS = (
    ("a048_seed42", "A048", "go2_g_a048_a033_lin_vel_z_m125", 42),
    ("a043_seed43", "A043", "go2_g_a043_a033_lin_vel_z_m15", 43),
    ("a043_seed44", "A043", "go2_g_a043_a033_lin_vel_z_m15", 44),
)
PURPOSE = {
    "a048_seed42": "다른 PC에서 A048과 동일 보상으로 얻는 비교 기준. 학습 변동의 크기·상한이 아니며 효과 판정 문턱으로 쓰지 않는다.",
    "a043_seed43": "A043 보상의 독립 재학습. 15cm 계단 이득의 재현과 복합 우회전 결함의 분리 여부를 본다.",
    "a043_seed44": "A043 보상의 독립 재학습. 15cm 계단 이득의 재현과 복합 우회전 결함의 분리 여부를 본다.",
}
READOUT = {
    "base_row": "a048_seed42 는 서버 A048 과의 차이를 같은 지표로 기록만 한다. G-A057 행은 이 행과 먼저 비교하고, "
                "서버 A048 대비 결과·기존 사전등록 판정도 따로 유지한다. 두 비교가 충돌하면 그대로 공개한다.",
    "individual_policy": "15cm stairs_15_down >=2단 >=50/96 이고 combined_yaw_right 자세 낙상 <=5/96 이면 공동 개선 후보로 "
                         "전 축 검증 대상(다른 seed 결과와 무관). 채택 기준이 아니다.",
    "setting_reproducibility": {"reproduced": "두 A043 seed 모두 15cm >=50", "degraded": "두 seed 모두 <=10",
                                "inconclusive": "그 밖(11~49 또는 두 seed 상반). 추가 학습 자동 금지"},
    "yaw_right_defect": {"reproduced": ">=15/96", "partial": "6~14", "protected": "<=5"},
    "thresholds": "이번 탐색용 기준이며 관측에서 나온 자연 경계가 아니다. 기존 A033 대조 채택 기준을 대체하지 않는다.",
    "causal_claims": "단일 학습 결과이므로 관측된 성능 차이로만 보고한다.",
    "submission": "다른 PC 정책은 탐색용이며 제출 후보가 아니다(R-6·제14조). 서버 재학습은 별도 판단.",
}


def weights6(arm: str) -> dict[str, float]:
    w = planmod.reward_weights((planmod.KEEP / arm / "training/env.yaml").read_text(encoding="utf-8"))
    return {k: float(w[k]) for k in REWARD_NAMES}


def run_config(template: str, key: str, seed: int) -> str:
    repl = {
        "WORK_ID": WORK_ID,
        "RUN_ID": f"train_G-A058-Go2_{key}_1000",
        "EXPERIMENT_SLUG": f"go2_g_a058_{key}",
        "KEEP_DIR_NAME": f"go2_g_a058_{key}",
        "RESULT_ZIP_NAME": f"GO2_G_A058_{key.upper()}_RESULT.zip",
        "DONE_MARKER": f"'[DONE] GO2_G_A058_{key.upper()}_RESULT_READY'",
        "TMUX_NAME": f"go2_g_a058_{key}",
        "TRAIN_SEED": str(seed),
        "SINGLE_CHANGE_NAME": "train_seed",
        "SINGLE_CHANGE_FROM": "42",
        "SINGLE_CHANGE_TO": str(seed),
    }
    lines = []
    for line in template.splitlines():
        if line.startswith("# generated by"):
            lines.append("# generated by tools/build_go2_g_a058_replicate_package.py (G-A058 replicate arm); do not edit")
            continue
        m = re.match(r"^([A-Z_]+)=", line)
        if m and m.group(1) in repl:
            lines.append(f"{m.group(1)}={repl.pop(m.group(1))}")
        else:
            lines.append(line)
    if repl:
        raise ValueError(f"run_config template lacks {sorted(repl)}")
    return "\n".join(lines) + "\n"


def arm_files(src: dict[str, bytes], key: str, label: str, arm: str, seed: int, sentinel6: dict) -> dict[str, bytes]:
    w6 = weights6(arm)
    template = src["candidate/quadruped_rewards.py"].decode("utf-8")
    rew_src = render_reward_source(template, w6)
    if reward_dict(rew_src) != w6:
        raise ValueError(f"{key}: rendered reward file does not parse back")
    expected = {"baseline": sentinel6, "candidate": w6}
    experiment = {
        "schema": "go2_replicate_arm_v1", "work_id": WORK_ID, "run_key": key,
        "purpose": PURPOSE[key], "promotion": "forbidden_other_pc_exploration",
        "reward_base": {"label": label, "arm": arm, "rewards": w6, "source": f"workspace/_keep/{arm}/training/env.yaml"},
        "reward_change": "none",
        "training": {"seed": seed, "num_envs": 4096, "max_iterations": 1000, "from_scratch": True},
        "evaluation": {"checkpoint_iter": 900, "seeds": [101, 202, 303], "case_count": 69,
                       "sentinel": "G-A033 stored arm, 5 cases (runner default)"},
        "runner": f"{a057.RUNNER} from upload/G-A055/current (v2) bytes unchanged, --inner, GO2_STAGE=full",
        "readout": READOUT, "proposal": PROPOSAL,
    }
    readme = (f"G-A058 replicate arm {key}\n"
              f"{label} 학습 보상 그대로(보상 변경 없음), 학습 seed {seed}, 4096 env, 1000 iter, 평가 iter 900, 69 case.\n"
              "이 폴더는 run_sweep.sh 가 펼쳐서 쓴다. 혼자 실행하지 않는다. 다른 PC 결과는 탐색용이며 제출 후보가 아니다.\n")
    return {
        "candidate/quadruped_rewards.py": rew_src.encode("utf-8"),
        "reference/baseline_quadruped_rewards.py": rew_src.encode("utf-8"),
        "reference/reward_base_quadruped_rewards.py": rew_src.encode("utf-8"),
        "expected_rewards.json": (json.dumps(expected, indent=2) + "\n").encode("utf-8"),
        "run_config.env": run_config(src["run_config.env"].decode("utf-8"), key, seed).encode("utf-8"),
        "experiment.json": (json.dumps(experiment, ensure_ascii=False, indent=1) + "\n").encode("utf-8"),
        "README.txt": readme.encode("utf-8"),
    }


def plan_md(rows: list[dict]) -> str:
    lines = ["# G-A058 보상 무변경 재학습 — 실행 목록과 판독 기준", "",
             f"근거·순서: `{PROPOSAL}` (Codex 합의 2026-09-30). 다른 PC에서 G-A057 나머지 11행보다 먼저 돈다.", ""]
    for r in rows:
        lines.append(f"- {r['key']}: {r['label']} 보상 그대로, 학습 seed {r['seed']} — {PURPOSE[r['key']]}")
    lines += ["", "## 판독 기준 (결과를 보기 전에 고정)"]
    for k, v in READOUT.items():
        lines.append(f"- {k}: {json.dumps(v, ensure_ascii=False) if isinstance(v, dict) else v}")
    return "\n".join(lines) + "\n"


def guide(zip_sha: str | None) -> str:
    return f"""GO2 G-A058 보상 무변경 재학습 — 다른 PC 실행 안내
================================================

목적: G-A057 나머지 11행보다 먼저 세 학습을 돈다. 보상은 바꾸지 않는다.
  a048_seed42  A048 보상, 학습 seed 42 — 다른 PC의 동일 보상 비교 기준(효과 판정 문턱 아님)
  a043_seed43  A043 보상, 학습 seed 43 — 계단 이득 재현·우회전 결함 분리
  a043_seed44  A043 보상, 학습 seed 44 — 같음
근거: {PROPOSAL}

환경·실패 처리·회수는 G-A057 안내(GO2_G_A057_RUN_GUIDE.txt)와 같다. 러너는 G-A055 v2 바이트 그대로다.

1. 올리기: {RELEASE}.zip  SHA256 {zip_sha or '(발행 시 기록)'}  → /workspace/{RELEASE}.zip
2. 실행 — 한 줄
   unzip -oq /workspace/{RELEASE}.zip -d /workspace && bash /workspace/go2_g_a058/run_sweep.sh
   목록만: bash /workspace/go2_g_a058/run_sweep.sh --list    진행: tmux attach -t go2_g_a058
   상태 표: /workspace/_keep/go2_g_a058_sweep/SWEEP_STATUS.tsv   재개: 같은 명령을 다시 친다.
3. 예상: 서버 GPU 기준 한 실행 약 90~95분, 세 실행 약 4.5~5시간. 다른 GPU에서는 달라진다.
4. 끝나면 G-A057을 이어서 돈다: bash /workspace/go2_g_a057/run_sweep.sh (완료 행은 SKIP_DONE).
5. 가져올 것: /workspace/_keep/go2_g_a058_<key>/ 폴더 전체, GO2_G_A058_<KEY>_RESULT.zip + .sha256,
   /workspace/_keep/go2_g_a058_sweep/ → 로컬 C:\\dev\\Nconnect\\workspace\\_keep\\ 에 같은 이름으로 복사.
6. 규정: 다른 PC 학습은 탐색용이다. 제출 정책은 서버에서 다시 학습한다. 배포 학습 코드는 수정하지 않았다.
"""


def build() -> tuple[bytes, dict]:
    src = a057.source_payload()
    sentinel6 = a057.six(json.loads(src["expected_rewards.json"])["baseline"])
    shared = a057.shared_files(src)
    files: dict[str, bytes] = {"shared/" + k: v for k, v in shared.items()}
    order, rows = [], []
    for key, label, arm, seed in ROWS:
        a = arm_files(src, key, label, arm, seed, sentinel6)
        a["PACKAGE_SHA256SUMS.txt"] = a057.sums({**shared, **a})
        for k, v in a.items():
            files[f"runs/{key}/{k}"] = v
        cfg = a["run_config.env"].decode("utf-8")
        keep = re.search(r"^KEEP_DIR_NAME=(.*)$", cfg, re.M).group(1)
        zipn = re.search(r"^RESULT_ZIP_NAME=(.*)$", cfg, re.M).group(1)
        order.append(f"{key} {keep} {zipn}")
        rows.append({"key": key, "label": label, "arm": arm, "seed": seed, "rewards": weights6(arm)})
    files["sweep_order.txt"] = ("\n".join(order) + "\n").encode("utf-8")
    files["run_sweep.sh"] = LAUNCHER.read_bytes().replace(b"\r\n", b"\n")
    files["SWEEP_PLAN.json"] = (json.dumps({"work_id": WORK_ID, "rows": rows, "readout": READOUT,
                                            "proposal": PROPOSAL}, ensure_ascii=False, indent=1) + "\n").encode("utf-8")
    files["SWEEP_PLAN.md"] = plan_md(rows).encode("utf-8")
    files["SWEEP_README.txt"] = guide(None).encode("utf-8")
    files["SWEEP_SHA256SUMS.txt"] = a057.sums(dict(files))
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name in sorted(files):
            info = zipfile.ZipInfo(PREFIX + name, FIXED_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (0o755 if name.endswith(".sh") else 0o644) << 16
            z.writestr(info, files[name])
    return buf.getvalue(), {"rows": rows, "files": files, "shared": shared}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    data, info = build()
    zsha = a057.sha(data)
    print(f"arms {len(info['rows'])}, files {len(info['files'])}, zip {len(data)} bytes, sha256 {zsha}")
    if args.check:
        return 0
    UPLOAD.mkdir(parents=True, exist_ok=True)
    (UPLOAD / f"{RELEASE}.zip").write_bytes(data)
    (UPLOAD / f"{RELEASE}.zip.sha256").write_text(f"{zsha}  {RELEASE}.zip\n", encoding="utf-8", newline="\n")
    (UPLOAD / "GO2_G_A058_RUN_GUIDE.txt").write_text(guide(zsha), encoding="utf-8", newline="\n")
    print(f"published {UPLOAD / (RELEASE + '.zip')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
