#!/usr/bin/env python3
"""PC2 단일 점 탐색 패키지 빌더 (2026-10-02).

설계: workspace/training/quadruped/upload/plan/GO2_PC2_DENSE_SWEEP_PROPOSAL_20261002.md §13·§14 (Codex 수용).
  - A048 보상(학습 env.yaml) 위 한 항 변경 점들의 최대 목록과 기준선 B1(A048 그대로)을 한 ZIP 에 담는다.
  - 러너 run_point.sh 는 지정한 한 점만 돌고 멈춘다. 다음 점은 판독 뒤 따로 정한다(자동 연결 없음).
  - G-A057·G-A058 과 같은 방식: G-A055 v2 패키지의 per-arm 러너·배포 코드·평가기·registry·G-A033 sentinel 을
    바이트 그대로 쓰고, 점마다 보상 파일·run_config.env·설명 파일만 바꾼다(R-6: 보상 가중치 외 학습 코드 불변).
  - 이름에 pc2 를 넣어 PC1(G-A057·G-A058) 폴더·ZIP·상태 폴더·tmux 와 겹치지 않게 한다.

번호는 발행 직전에 원장·upload 를 확인해 확정한다(§14-3). 빌드·테스트는 잠정 번호로 하고, 발행은 --publish --work-id 를 명시해야 한다.
    python -B tools/build_go2_pc2_point_package.py --check                       # 빌드만(잠정 번호)
    python -B tools/build_go2_pc2_point_package.py --publish --work-id G-A0NN    # 미사용 번호 확인 후 발행
"""
from __future__ import annotations

import argparse
import io
import json
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GO2 = ROOT / "workspace/training/quadruped"
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(GO2))
import build_go2_g_a057_sweep_package as a057  # noqa: E402
import go2_g_a057_sweep_plan as planmod  # noqa: E402
from go2_tuning_config import REWARD_NAMES, reward_dict, render_reward_source  # noqa: E402

PROVISIONAL_WORK_ID = "G-A060"  # 잠정. 발행 시 --work-id 로 확정한다.
LAUNCHER = ROOT / "tools/go2_pc2_run_point.sh"
DESIGN = "workspace/training/quadruped/upload/plan/GO2_PC2_DENSE_SWEEP_PROPOSAL_20261002.md"
BASE_ARM = planmod.BASE_ARM  # go2_g_a048_a033_lin_vel_z_m125 (A048)
FIXED_TIME = (2026, 10, 2, 0, 0, 0)

# 최대 목록(§13-1). 목록에 있다는 것은 실행 선정이 아니다(§14-2-4).
B1_KEY = "a048_seed42"
POINTS: tuple[tuple[str, str | None, float | None, str], ...] = (
    (B1_KEY, None, None, "기준선 B1 — PC2 A048 그대로. PC2 점들의 직접 대조군."),
    ("ang_vel_xy_l2_m0p06", "ang_vel_xy_l2", -0.06, "조건부(§13-1): −0.08 이 표적 개선 + 세 seed 공통 보호 손실일 때만 검토 자격."),
    ("ang_vel_xy_l2_m0p07", "ang_vel_xy_l2", -0.07, "−0.06 결과를 보고 따로 정한다."),
    ("ang_vel_xy_l2_m0p08", "ang_vel_xy_l2", -0.08, "첫 후보(§14-1). G-A057 같은 행과 보상 바이트 동일."),
    ("ang_vel_xy_l2_m0p1", "ang_vel_xy_l2", -0.10, "자동 확장 없음. 완료점 결과로 따로 정한다."),
    ("ang_vel_xy_l2_m0p12", "ang_vel_xy_l2", -0.12, "자동 확장 없음. 완료점 결과로 따로 정한다."),
    ("track_lin_vel_xy_exp_p1p3", "track_lin_vel_xy_exp", 1.3, "자동 확장 없음."),
    ("track_lin_vel_xy_exp_p1p4", "track_lin_vel_xy_exp", 1.4, "다음 우선 검토점(§14-1). G-A057 같은 행과 보상 바이트 동일."),
    ("track_lin_vel_xy_exp_p1p45", "track_lin_vel_xy_exp", 1.45, "자동 확장 없음."),
    ("track_lin_vel_xy_exp_p1p55", "track_lin_vel_xy_exp", 1.55, "자동 확장 없음."),
    ("track_lin_vel_xy_exp_p1p6", "track_lin_vel_xy_exp", 1.6, "자동 확장 없음. G-A057 같은 행과 보상 바이트 동일."),
)
# G-A057 에도 있는 점 → 그 행 key (장비 간 재현 비교, 평균 금지)
SAME_AS_G_A057 = {"ang_vel_xy_l2_m0p08": "ang_vel_xy_l2_m0p08", "track_lin_vel_xy_exp_p1p4": "track_lin_vel_xy_exp_p1p4",
                  "track_lin_vel_xy_exp_p1p6": "track_lin_vel_xy_exp_p1p6"}


def names(work_id: str) -> dict[str, str]:
    if not re.fullmatch(r"G-A\d{3}", work_id):
        raise ValueError(f"work id must look like G-A0NN: {work_id}")
    slug = work_id.lower().replace("-", "_")          # g_a060
    up = work_id.upper().replace("-", "_")            # G_A060
    return {"work_id": work_id, "slug": slug, "up": up,
            "prefix": f"go2_{slug}_pc2/",
            "release": f"GO2_{up}_PC2_a048_points_v1",
            "status_dir": f"go2_{slug}_pc2_points",
            "work_dir": f"/workspace/go2_{slug}_pc2_work",
            "tmux": f"go2_{slug}_pc2"}


def base6() -> dict[str, float]:
    w = planmod.reward_weights((planmod.KEEP / BASE_ARM / "training/env.yaml").read_text(encoding="utf-8"))
    return {k: float(w[k]) for k in REWARD_NAMES}


def point_rewards(var: str | None, value: float | None) -> dict[str, float]:
    w = base6()
    if var is not None:
        w[var] = float(value)
    return w


def run_config(template: str, n: dict, key: str, var: str | None, value: float | None, b6: dict) -> str:
    keep = f"go2_{n['slug']}_pc2_{key}"
    zipn = f"GO2_{n['up']}_PC2_{key.upper()}_RESULT.zip"
    repl = {
        "WORK_ID": n["work_id"],
        "RUN_ID": f"train_{n['work_id']}-Go2_pc2_{key}_1000",
        "EXPERIMENT_SLUG": keep,
        "KEEP_DIR_NAME": keep,
        "RESULT_ZIP_NAME": zipn,
        "DONE_MARKER": f"'[DONE] GO2_{n['up']}_PC2_{key.upper()}_RESULT_READY'",
        "TMUX_NAME": keep,
        "TRAIN_SEED": "42",
        "SINGLE_CHANGE_NAME": var or "train_seed",
        "SINGLE_CHANGE_FROM": f"{b6[var]:g}" if var else "42",
        "SINGLE_CHANGE_TO": f"{value:g}" if var else "42",
    }
    lines = []
    for line in template.splitlines():
        if line.startswith("# generated by"):
            lines.append("# generated by tools/build_go2_pc2_point_package.py (PC2 single-point arm); do not edit")
            continue
        m = re.match(r"^([A-Z_]+)=", line)
        if m and m.group(1) in repl:
            lines.append(f"{m.group(1)}={repl.pop(m.group(1))}")
        else:
            lines.append(line)
    if repl:
        raise ValueError(f"run_config template lacks {sorted(repl)}")
    return "\n".join(lines) + "\n"


def arm_files(src: dict[str, bytes], n: dict, key: str, var: str | None, value: float | None,
              note: str, sentinel6: dict) -> dict[str, bytes]:
    b6 = base6()
    c6 = point_rewards(var, value)
    changed = [k for k in REWARD_NAMES if c6[k] != b6[k]]
    if changed != ([var] if var else []):
        raise ValueError(f"{key}: must change exactly {var}, changed {changed}")
    template = src["candidate/quadruped_rewards.py"].decode("utf-8")
    cand_src, base_src = render_reward_source(template, c6), render_reward_source(template, b6)
    if reward_dict(cand_src) != c6 or reward_dict(base_src) != b6:
        raise ValueError(f"{key}: rendered reward file does not parse back")
    experiment = {
        "schema": "go2_pc2_point_v1", "work_id": n["work_id"], "device": "PC2", "run_key": key,
        "role": "baseline_B1" if var is None else "single_change_point",
        "note": note, "promotion": "forbidden_pc_exploration",
        "selection": "최대 목록의 한 점. 목록에 있다는 것은 실행 선정이 아니다. 다음 점은 판독 뒤 따로 정한다.",
        "reward_base": {"label": "A048", "arm": BASE_ARM, "rewards": b6},
        "single_change": None if var is None else {"name": var, "from": b6[var], "to": float(value)},
        "rewards": c6,
        "same_setting_as_g_a057_row": SAME_AS_G_A057.get(key),
        "training": {"seed": 42, "num_envs": 4096, "max_iterations": 1000, "from_scratch": True},
        "evaluation": {"checkpoint_iter": 900, "seeds": [101, 202, 303], "case_count": 69,
                       "sentinel": "G-A033 stored arm, 5 cases (runner default)"},
        "comparison": "PC2 B1 대비로만 읽는다. PC1·서버 결과와 평균내지 않는다.",
        "readout": "tools/go2_pc2_point_readout.py", "design": DESIGN,
        "runner": f"{a057.RUNNER} from upload/G-A055/current (v2) bytes unchanged, --inner, GO2_STAGE=full",
    }
    change = "보상 변경 없음" if var is None else f"{var} {b6[var]:g} -> {value:g}"
    readme = (f"{n['work_id']} PC2 point {key}\nA048 보상 위 {change}. 학습 seed 42, 4096 env, 1000 iter, 평가 iter 900, 69 case.\n"
              "이 폴더는 run_point.sh 가 펼쳐서 쓴다. 혼자 실행하지 않는다. PC 결과는 탐색용이며 제출 후보가 아니다.\n")
    return {
        "candidate/quadruped_rewards.py": cand_src.encode("utf-8"),
        "reference/baseline_quadruped_rewards.py": base_src.encode("utf-8"),
        "reference/reward_base_quadruped_rewards.py": base_src.encode("utf-8"),
        "expected_rewards.json": (json.dumps({"baseline": sentinel6, "candidate": c6}, indent=2) + "\n").encode("utf-8"),
        "run_config.env": run_config(src["run_config.env"].decode("utf-8"), n, key, var, value, b6).encode("utf-8"),
        "experiment.json": (json.dumps(experiment, ensure_ascii=False, indent=1) + "\n").encode("utf-8"),
        "README.txt": readme.encode("utf-8"),
    }


def guide(n: dict, zip_sha: str | None) -> str:
    lines = "\n".join(f"  {k:30s} {('보상 변경 없음' if v is None else f'{v} {x:g}'):34s} {note}" for k, v, x, note in POINTS)
    return f"""GO2 {n['work_id']} PC2 단일 점 탐색 — 실행 안내
==================================================

설계: {DESIGN} §13·§14
한 번에 한 점만 돈다. 점이 끝나면 멈춘다. 다음 점은 판독 뒤 따로 정한다(자동 연결 없음).
목록은 최대 목록이며, 목록에 있다는 것은 실행 선정이 아니다.

점 목록 (A048 보상 기준, 학습 seed 42, 4096 env, 1000 iter, 평가 iter 900, 69 case):
{lines}

0. 실행 전: PC2 환경 기록(GO2_PC2_ENV_<날짜>.md)·smoke·속도 실측, 탐색 마감 시각과 회수 여유를 정한다(§13-4).
1. 올리기: {n['release']}.zip  SHA256 {zip_sha or '(발행 시 기록)'}  → /workspace/{n['release']}.zip
2. 첫 점(B1):
   unzip -oq /workspace/{n['release']}.zip -d /workspace && bash /workspace/{n['prefix']}run_point.sh --only {B1_KEY}
   목록·상태: bash /workspace/{n['prefix']}run_point.sh --list    진행: tmux attach -t {n['tmux']}
   끊기면 같은 --only 명령을 다시 친다(부분 결과는 GO2_RESUME=1 로 이어 간다).
3. 다음 점: 판독 뒤 정해진 key 로 bash /workspace/{n['prefix']}run_point.sh --only <key>
4. 가져올 것: /workspace/_keep/go2_{n['slug']}_pc2_<key>/ 폴더 전체, GO2_{n['up']}_PC2_<KEY>_RESULT.zip + .sha256,
   /workspace/_keep/{n['status_dir']}/ → 저장소 workspace/_keep/ 에 같은 이름으로 복사(원본 유지).
5. 규정: PC 학습은 탐색용이다. 제출 정책은 서버에서 다시 학습한다. 배포 학습 코드는 수정하지 않았다.
"""


def plan_json(n: dict) -> dict:
    b6 = base6()
    return {"work_id": n["work_id"], "device": "PC2", "design": DESIGN, "base_arm": BASE_ARM, "base_rewards": b6,
            "points": [{"key": k, "variable": v, "value": x, "note": note, "same_as_g_a057": SAME_AS_G_A057.get(k)}
                       for k, v, x, note in POINTS],
            "selection_rule": "한 점씩. 다음 점·확장·방향 전환·조합은 완료점의 표적·보호 결과와 남은 비용을 보고 Codex 가 정한다.",
            "readout": "tools/go2_pc2_point_readout.py (§13-2 + §14-2)"}


def build(work_id: str = PROVISIONAL_WORK_ID) -> tuple[bytes, dict]:
    n = names(work_id)
    src = a057.source_payload()
    sentinel6 = a057.six(json.loads(src["expected_rewards.json"])["baseline"])
    shared = a057.shared_files(src)
    files: dict[str, bytes] = {"shared/" + k: v for k, v in shared.items()}
    lines = []
    for key, var, value, note in POINTS:
        a = arm_files(src, n, key, var, value, note, sentinel6)
        a["PACKAGE_SHA256SUMS.txt"] = a057.sums({**shared, **a})
        for k, v in a.items():
            files[f"runs/{key}/{k}"] = v
        cfg = a["run_config.env"].decode("utf-8")
        keep = re.search(r"^KEEP_DIR_NAME=(.*)$", cfg, re.M).group(1)
        zipn = re.search(r"^RESULT_ZIP_NAME=(.*)$", cfg, re.M).group(1)
        lines.append(f"{key} {keep} {zipn}")
    files["points.txt"] = ("\n".join(lines) + "\n").encode("utf-8")
    files["point_config.env"] = (f"POINT_WORK_ID={n['work_id']}\nPOINT_STATUS_DIR_NAME={n['status_dir']}\n"
                                 f"POINT_WORK_DIR={n['work_dir']}\nPOINT_TMUX_NAME={n['tmux']}\n").encode("utf-8")
    files["run_point.sh"] = LAUNCHER.read_bytes().replace(b"\r\n", b"\n")
    files["POINT_PLAN.json"] = (json.dumps(plan_json(n), ensure_ascii=False, indent=1) + "\n").encode("utf-8")
    files["README.txt"] = guide(n, None).encode("utf-8")
    files["SHA256SUMS.txt"] = a057.sums(dict(files))
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name in sorted(files):
            info = zipfile.ZipInfo(n["prefix"] + name, FIXED_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (0o755 if name.endswith(".sh") else 0o644) << 16
            z.writestr(info, files[name])
    return buf.getvalue(), {"names": n, "files": files, "shared": shared}


def id_in_use(work_id: str) -> list[str]:
    hits = []
    if (GO2 / "upload" / work_id).exists():
        hits.append(f"upload/{work_id} exists")
    ledger = ROOT / "ARTIFACT_MANAGEMENT.md"
    if ledger.is_file() and re.search(rf"\b{re.escape(work_id)}\b", ledger.read_text(encoding="utf-8")):
        hits.append(f"{work_id} appears in ARTIFACT_MANAGEMENT.md")
    return hits


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="build only")
    ap.add_argument("--publish", action="store_true", help="write the ZIP to upload/<work-id>/current")
    ap.add_argument("--work-id", help="required with --publish; must be unused")
    args = ap.parse_args(argv)
    if args.publish and not args.work_id:
        ap.error("--publish needs --work-id (번호는 발행 직전에 확인해 확정한다)")
    work_id = args.work_id or PROVISIONAL_WORK_ID
    data, info = build(work_id)
    zsha = a057.sha(data)
    print(f"work id {work_id}{'' if args.work_id else ' (provisional)'}, points {len(POINTS)}, "
          f"files {len(info['files'])}, zip {len(data)} bytes, sha256 {zsha}")
    if not args.publish:
        return 0
    hits = id_in_use(work_id)
    if hits:
        print("[REFUSED] work id already used: " + "; ".join(hits))
        return 2
    n = info["names"]
    up = GO2 / "upload" / work_id / "current"
    up.mkdir(parents=True, exist_ok=True)
    (up / f"{n['release']}.zip").write_bytes(data)
    (up / f"{n['release']}.zip.sha256").write_text(f"{zsha}  {n['release']}.zip\n", encoding="utf-8", newline="\n")
    (up / f"GO2_{n['up']}_PC2_RUN_GUIDE.txt").write_text(guide(n, zsha), encoding="utf-8", newline="\n")
    print(f"published {up / (n['release'] + '.zip')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
