#!/usr/bin/env bash
# G-A028 P1: frozen-policy video diagnosis, NOT reward training.
set -euo pipefail
PACKAGE_ROOT=${PACKAGE_ROOT:-/workspace/GO2_G_A028_P1}
ISAACLAB=${ISAACLAB:-/workspace/IsaacLab/isaaclab.sh}
KEEP=/workspace/_keep/GO2_G_A028_P1
RESULT_ZIP=/workspace/_keep/GO2_G_A028_RESULT.zip
TMUX_NAME=go2_G_A028
export PATH=/usr/bin:$PATH
[[ -x "$ISAACLAB" ]] || { echo '[FAIL] IsaacLab missing'; exit 2; }
(cd "$PACKAGE_ROOT" && sha256sum -c PACKAGE_SHA256SUMS.txt)
if [[ "${1:-}" != --inner ]]; then
  command -v tmux >/dev/null
  if [[ -e "$KEEP" || -e "$RESULT_ZIP" ]] || tmux has-session -t "$TMUX_NAME" 2>/dev/null; then
    echo '[BLOCKED] existing G-A028 results/session; preserve and download them'; exit 2
  fi
  if pgrep -af 'train.py|play.py'; then echo '[BLOCKED] robot process active'; exit 2; fi
  mkdir -p "$KEEP"
  printf -v launch 'cd %q && PACKAGE_ROOT=%q ISAACLAB=%q bash server_run_GO2_G_A028.sh --inner' "$PACKAGE_ROOT" "$PACKAGE_ROOT" "$ISAACLAB"
  tmux new-session -d -s "$TMUX_NAME" "$launch"
  echo '[STARTED] go2_G_A028; monitor: tmux attach -t go2_G_A028'
  exit 0
fi
mkdir -p "$KEEP/logs" "$KEEP/policy" "$KEEP/meta" "$KEEP/evaluation"
exec > >(tee "$KEEP/launcher.log") 2>&1
package_result() {
  local state=$1
  printf 'WORK_ID=G-A028\nTRAINING=none\nRESULT_STATE=%s\nVIDEO_STATUS=VIDEO_UNKNOWN\n' "$state" >"$KEEP/RESULT_STATUS.txt"
  cp "$KEEP/launcher.log" "$KEEP/launcher.snapshot.log"
  (cd "$KEEP" && find . -type f ! -name launcher.log ! -name SHA256SUMS.txt -print0 | sort -z | xargs -0 sha256sum >SHA256SUMS.txt)
  "$ISAACLAB" -p "$PACKAGE_ROOT/package_go2_result.py" "$KEEP" "$RESULT_ZIP"
  sha256sum "$RESULT_ZIP" >"$RESULT_ZIP.sha256"
  echo "[DOWNLOAD] $RESULT_ZIP and $RESULT_ZIP.sha256"
}
on_exit() {
  local rc=$?
  trap - EXIT
  printf 'RUNNER_RC=%s\n' "$rc" >"$KEEP/RUNNER_STATUS.txt"
  if [[ "$rc" != 0 ]]; then package_result PARTIAL || true; fi
}
trap on_exit EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
cp "$PACKAGE_ROOT/P1_SPEC.json" "$PACKAGE_ROOT/PACKAGE_SHA256SUMS.txt" "$KEEP/meta/"
cp "$PACKAGE_ROOT"/*.sh "$KEEP/meta/"
source "$PACKAGE_ROOT/a027_case_definitions.sh"
# The original training report is not regenerated by evaluation.
printf 'TRAINING=none\nA017_TRAINING_REPORT=MISSING\nPILOT_TRAINING_REPORT=READ_UNMATCHED\nNEW_TRAINING_REPORT=NOT_APPLICABLE\n' >"$KEEP/meta/REPORT_STATUS.txt"
for label in a017 pilot; do
  root="$PACKAGE_ROOT/$label"
  mkdir -p "$KEEP/policy/$label" "$KEEP/logs/$label" "$KEEP/evaluation/$label"
  cp "$root/exported/model_best.pt" "$root/exported/env.yaml" "$KEEP/policy/$label/"
  for seed in 101 202 303; do
    for case_id in stairs_10_down stairs_15_down slope_plus_20; do
      scenario=G5
      [[ "$case_id" != slope_plus_20 ]] || scenario=G4
      set_case "$case_id"
      out="$KEEP/evaluation/$label/${case_id}_seed_${seed}"
      mkdir -p "$out"
      # Clear only generated exports in this package's isolated replay directory.
      cd "$root"
      rm -f -- exported/play_video.mp4
      cp "$KEEP/policy/$label/model_best.pt" "$KEEP/policy/$label/env.yaml" exported/
      sha256sum exported/model_best.pt exported/env.yaml go2_eval_telemetry.py >"$out/INPUT_SHA256SUMS.txt"
      cmd=("$ISAACLAB" -p play.py --task Quadruped-v0 --num_envs 4
        --headless --video --video_length 1000 --enable_cameras
        "agent.seed=$seed" 'env.commands.base_velocity.heading_command=false'
        'env.commands.base_velocity.rel_standing_envs=0.0'
        'env.commands.base_velocity.resampling_time_range=[1000.0,1000.0]'
        "env.commands.base_velocity.ranges.lin_vel_x=[$VX,$VX]"
        "env.commands.base_velocity.ranges.lin_vel_y=[$VY,$VY]"
        "env.commands.base_velocity.ranges.ang_vel_z=[$WZ,$WZ]" "${TERRAIN_ARGS[@]}")
      printf '%q ' "${cmd[@]}" >"$out/COMMAND.txt"
      printf '\nPOLICY=%s\nCASE=%s\nSCENARIO=%s\nSEED=%s\nNUM_ENVS=4\nSTEPS=1000\n' "$label" "$case_id" "$scenario" "$seed" >"$out/IDENTITY.txt"
      echo "[CASE] $label $case_id seed=$seed"
      set +e
      env -u NCRC_PLAY_PUSH_X -u NCRC_PLAY_PUSH_Y -u NCRC_EVAL_DR \
        NCRC_EVAL_OUT="$out" NCRC_EVAL_STEPS=1000 NCRC_EVAL_CASE="$case_id" \
        NCRC_EVAL_SCENARIO="$scenario" NCRC_EVAL_SEED="$seed" \
        "${cmd[@]}" 2>&1 | tee "$KEEP/logs/$label/${case_id}_seed_${seed}.log"
      rc=${PIPESTATUS[0]}
      set -e
      printf 'PLAY_RC=%s\n' "$rc" >"$out/PLAY_STATUS.txt"
      # Recover video even when telemetry validation fails.
      if [[ -s exported/play_video.mp4 ]]; then cp exported/play_video.mp4 "$out/play_video.mp4"; fi
      [[ "$rc" == 0 && -s "$out/play_video.mp4" && -s "$out/summary.json" && -s "$out/steps.csv" ]] || exit 5
      grep -qx EVAL_RC=0 "$out/STATUS.txt"
      grep -qx STEPS=1000 "$out/STATUS.txt"
      grep -qx ROWS=4000 "$out/STATUS.txt"
      [[ "$(wc -l < "$out/steps.csv")" == 4001 ]] || exit 5
      "$ISAACLAB" -p "$PACKAGE_ROOT/posture_contract_check.py" "$out/summary.json"
    done
  done
done
printf 'RUNNER_RC=0\n' >"$KEEP/RUNNER_STATUS.txt"
package_result FULL
trap - EXIT
echo '[DONE] GO2_G_A028_P1_RESULT_READY'
